# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            CTi Winnipeg
tagline:          Canadian Tire Innovations
url:              http://cti.to
paginate:         1
baseurl:          /
excerpt_separator: ""
author:
  name:           Richard Bennett
  url:            http://cti.io/
  email:          richard.bennett.cti@gmail.com

# Custom vars
version:          1.0.0
github:           richard-bennett-cti